package GooReadbackFixture

import Goo

class EffectsCell : Cell {
  shared {
    let Root ElementHandle = ElementHandle{}
    let ShadowContainer ElementHandle = ElementHandle{}
    let ShadowButton ElementHandle = ElementHandle{}
    let ShapeShadow ElementHandle = ElementHandle{}
    let GroupOuter ElementHandle = ElementHandle{}
    let GroupInner ElementHandle = ElementHandle{}
    let ClipViewport ElementHandle = ElementHandle{}
    let ClipLeaf ElementHandle = ElementHandle{}
    let ColorGlyph ElementHandle = ElementHandle{}
    let BlendMultiply ElementHandle = ElementHandle{}
    let BlendScreen ElementHandle = ElementHandle{}
    let BlendOverlay ElementHandle = ElementHandle{}
    let BlendDifference ElementHandle = ElementHandle{}
    let DiamondPath VectorPath = PathBuilder().MoveTo(0.5, 0.0).LineTo(1.0, 0.5).LineTo(0.5, 1.0).LineTo(0.0, 0.5).Close().Build()
  }

  override func Build() Blob -> Container() {.Width: Length.Percent(100),.Height: Length.Percent(100),.Handle: EffectsCell.Root,.Position: PositionType.Relative,.BackgroundColor: Color.Rgb(12, 20, 32),
    Container{
        Position: PositionType.Absolute,
        Left: 14,
        Top: 14,
        Width: 112,
        Height: 88,
        Handle: EffectsCell.ShadowContainer,
        BorderRadius: 16,
        BorderStyle: BorderStyle.Solid,
        BorderTopWidth: 2,
        BorderRightWidth: 2,
        BorderBottomWidth: 2,
        BorderLeftWidth: 2,
        BorderColor: Color.Rgb(82, 176, 224),
        OutlineWidth: 3,
        OutlineOffset: 2,
        OutlineColor: Color.Rgb(232, 196, 72),
        BoxShadows: []BoxShadow{
          BoxShadow{
            OffsetX: 3,
            OffsetY: 4,
            Blur: 8,
            Spread: 2,
            Color: Color.Rgba(0, 0, 0, 190),
          },
          BoxShadow{
            OffsetX: -2,
            OffsetY: -2,
            Blur: 3,
            Spread: 0,
            Color: Color.Rgba(72, 128, 224, 180),
          },
          BoxShadow{
            OffsetX: 0,
            OffsetY: 0,
            Blur: 4,
            Spread: 2,
            Color: Color.Rgba(224, 72, 72, 180),
            Inset: true,
          },
        },
        BackgroundColor: Color.Rgb(44, 92, 132),
      },
      Button() {.Position: PositionType.Absolute,.Left: 144,.Top: 14,.Width: 112,.Height: 88,.Handle: EffectsCell.ShadowButton,.BorderRadius: 16,.BoxShadows: []BoxShadow{
          BoxShadow{
            OffsetX: 2,
            OffsetY: 3,
            Blur: 7,
            Spread: 1,
            Color: Color.Rgba(0, 0, 0, 190),
          },
          BoxShadow{
            OffsetX: 0,
            OffsetY: 0,
            Blur: 3,
            Spread: 1,
            Color: Color.Rgba(72, 224, 128, 160),
            Inset: true,
          },
        },.BackgroundColor: Color.Rgb(36, 116, 84),
      Text{
            Position: PositionType.Absolute,
            Left: 14,
            Top: 28,
            Content: "GOO",
            FontFamily: "ReadbackGateFont",
            FontSize: 22,
            Color: Color.White,
        },
      },
      Shape{
        Position: PositionType.Absolute,
        Left: 14,
        Top: 106,
        Width: 112,
        Height: 22,
        Handle: EffectsCell.ShapeShadow,
        Path: EffectsCell.DiamondPath,
        Fit: ShapeFit.Fill,
        FillRule: FillRule.NonZero,
        BorderWidth: 2,
        BorderColor: Color.Rgb(224, 232, 244),
        BoxShadows: []BoxShadow{
          BoxShadow{
            OffsetX: 3,
            OffsetY: 2,
            Blur: 4,
            Spread: 1,
            Color: Color.Rgba(0, 0, 0, 190),
          },
          BoxShadow{
            OffsetX: 0,
            OffsetY: 0,
            Blur: 2,
            Spread: 0,
            Color: Color.Rgba(72, 224, 196, 160),
            Inset: true,
          },
        },
        BackgroundColor: Color.Rgb(72, 128, 224),
      },
      Container() {.Position: PositionType.Absolute,.Left: 272,.Top: 14,.Width: 154,.Height: 88,.Handle: EffectsCell.GroupOuter,.Opacity: 0.65,
      Container() {.Width: Length.Percent(100),.Height: Length.Percent(100),.Handle: EffectsCell.GroupInner,.Opacity: 0.75,
        Container{
                Position: PositionType.Absolute,
                Left: 10,
                Top: 12,
                Width: 96,
                Height: 58,
                BackgroundColor: Color.Rgb(224, 64, 72),
              },
              Container{
                Position: PositionType.Absolute,
                Left: 48,
                Top: 20,
                Width: 96,
                Height: 58,
                BackgroundColor: Color.Rgb(72, 128, 224),
              },
            },
          },
    Container() {.Position: PositionType.Absolute,.Left: 14,.Top: 132,.Width: 132,.Height: 112,.Handle: EffectsCell.ClipViewport,.BorderRadius: 24,.Overflow: Overflow.Hidden,.ClipPath: EffectsCell.DiamondPath,.ClipPathFit: ShapeFit.Fill,.BackgroundColor: Color.Rgb(32, 84, 132),
      Container{
            Position: PositionType.Absolute,
            Left: 22,
            Top: 26,
            Width: 112,
            Height: 74,
            Handle: EffectsCell.ClipLeaf,
            Transform: PanelTransform{ Rotate: 18, ScaleX: 0.9, ScaleY: 1.1 },
            BackgroundColor: Color.Rgb(232, 196, 72),
        },
      },
      Text{
        Position: PositionType.Absolute,
        Left: 178,
        Top: 144,
        Width: 96,
        Height: 86,
        Handle: EffectsCell.ColorGlyph,
        Content: "\uE900",
        FontFamily: "ReadbackColor",
        FontSize: 64,
        Color: Color.White,
        TextStrokeWidth: 1,
        TextStrokeColor: Color.Rgb(232, 196, 72),
        TextShadow: TextShadow{
          OffsetX: 2,
          OffsetY: 2,
          Blur: 0,
          Color: Color.Rgba(0, 0, 0, 180),
        },
      },
      Text{
        Position: PositionType.Absolute,
        Left: 300,
        Top: 108,
        Width: 112,
        Height: 28,
        Content: "BLUR",
        FontFamily: "ReadbackGateFont",
        FontSize: 20,
        Color: Color.Rgb(224, 232, 244),
        TextShadow: TextShadow{
          OffsetX: 1,
          OffsetY: -1,
          Blur: 5,
          Color: Color.Rgba(232, 64, 196, 190),
        },
      },
      Text{
        Position: PositionType.Absolute,
        Left: 160,
        Top: 108,
        Width: 112,
        Height: 28,
        Content: "BOX",
        FontFamily: "ReadbackGateFont",
        FontSize: 20,
        Color: Color.Rgb(224, 232, 244),
        BoxShadow: BoxShadow{
          OffsetX: 4,
          OffsetY: 2,
          Blur: 0,
          Color: Color.Rgba(72, 224, 196, 180),
        },
      },
      Container() {.Position: PositionType.Absolute,.Left: 292,.Top: 142,.Width: 132,.Height: 92,.BorderRadius: 14,.OutlineWidth: 2,.OutlineOffset: -3,.OutlineColor: Color.Rgb(108, 224, 196),.BackgroundColor: Color.Rgb(24, 48, 72),.BoxShadows: []BoxShadow{
          BoxShadow{
            OffsetX: 0,
            OffsetY: 0,
            Blur: 0,
            Spread: 0,
            Color: Color.Rgba(232, 196, 72, 210),
            Inset: true,
          },
        },
      Text{
            Position: PositionType.Absolute,
            Left: 12,
            Top: 30,
            Content: "Readback",
            FontFamily: "ReadbackGateFont",
            FontSize: 24,
            Color: Color.Rgb(224, 232, 244),
          },
        },
    Container() {.Position: PositionType.Absolute,.Left: 14,.Top: 246,.Width: 96,.Height: 18,.BackgroundColor: Color.Rgb(224, 64, 72),
      Container{
            Position: PositionType.Absolute,
            Left: 24,
            Top: 3,
            Width: 68,
            Height: 12,
            Handle: EffectsCell.BlendMultiply,
            BlendMode: BlendMode.Multiply,
            BackgroundColor: Color.Rgb(72, 128, 224),
          },
        },
    Container() {.Position: PositionType.Absolute,.Left: 120,.Top: 246,.Width: 96,.Height: 18,.BackgroundColor: Color.Rgb(224, 64, 72),
      Container{
            Position: PositionType.Absolute,
            Left: 24,
            Top: 3,
            Width: 68,
            Height: 12,
            Handle: EffectsCell.BlendScreen,
            BlendMode: BlendMode.Screen,
            BackgroundColor: Color.Rgb(72, 128, 224),
          },
        },
    Container() {.Position: PositionType.Absolute,.Left: 226,.Top: 246,.Width: 96,.Height: 18,.BackgroundColor: Color.Rgb(224, 64, 72),
      Container{
            Position: PositionType.Absolute,
            Left: 24,
            Top: 3,
            Width: 68,
            Height: 12,
            Handle: EffectsCell.BlendOverlay,
            BlendMode: BlendMode.Overlay,
            BackgroundColor: Color.Rgb(72, 128, 224),
          },
        },
    Container() {.Position: PositionType.Absolute,.Left: 332,.Top: 246,.Width: 96,.Height: 18,.BackgroundColor: Color.Rgb(224, 64, 72),
      Container{
            Position: PositionType.Absolute,
            Left: 24,
            Top: 3,
            Width: 68,
            Height: 12,
            Handle: EffectsCell.BlendDifference,
            BlendMode: BlendMode.Difference,
            BackgroundColor: Color.Rgb(72, 128, 224),
          },
        },
      }
}
