using System;
using System.Collections.Generic;
using System.Reflection;
using Goo;
using Xunit;

public sealed class FixtureContractTests
{
    public static IEnumerable<object[]> Cases()
    {
        yield return Contract<AccessibilityFixtures>(nameof(AccessibilityFixtures.AdapterDeliveryThreadContract));
        yield return Contract<AccessibilityFixtures>(nameof(AccessibilityFixtures.DeclaredActionFailureContract));
        yield return Contract<AccessibilityFixtures>(nameof(AccessibilityFixtures.DeliveryDemandAndReplacementContract));
        yield return Contract<AccessibilityFixtures>(nameof(AccessibilityFixtures.DisplayAndVisibilityExclusionContract));
        yield return Contract<AccessibilityFixtures>(nameof(AccessibilityFixtures.FailedDiffPreservesPublishedTreeContract));
        yield return Contract<AccessibilityFixtures>(nameof(AccessibilityFixtures.FocusLayoutAndScrollContract));
        yield return Contract<AccessibilityFixtures>(nameof(AccessibilityFixtures.PrimitiveAndExclusionContract));
        yield return Contract<AccessibilityFixtures>(nameof(AccessibilityFixtures.RetainedIdentityAndRelationshipsContract));
        yield return Contract<AccessibilityFixtures>(nameof(AccessibilityFixtures.RetiredAndInvalidRelationshipContract));
        yield return Contract<AccessibilityFixtures>(nameof(AccessibilityFixtures.SnapshotAndSelectionContract));
        yield return Contract<AccessibilityFixtures>(nameof(AccessibilityFixtures.StateAndActionCapabilityContract));
        yield return Contract<AccessibilityFixtures>(nameof(AccessibilityFixtures.SyntheticRootAndPrimitiveActionContract));
        yield return Contract<AccessibilityFixtures>(nameof(AccessibilityFixtures.ValidationAndRetryContract));
        yield return Contract<CellFixtures>(nameof(CellFixtures.DirectChildQueuesCanonicalParentOnce));
        yield return Contract<CellFixtures>(nameof(CellFixtures.DirectCompositionAddsNoRenderNode));
        yield return Contract<CellFixtures>(nameof(CellFixtures.DirtyParentRunsBeforeAndSubsumesDirtyChild));
        yield return Contract<CellFixtures>(nameof(CellFixtures.DirtySiblingFailureResubmitsRemaining));
        yield return Contract<CellFixtures>(nameof(CellFixtures.DirtySiblingsRebuildOnceInOneUpdate));
        yield return Contract<CellFixtures>(nameof(CellFixtures.DisposesEachUnmountedCellExactlyOnce));
        yield return Contract<CellFixtures>(nameof(CellFixtures.FactoryBuildFailurePreservesPriorMount));
        yield return Contract<CellFixtures>(nameof(CellFixtures.FactoryKeyChangeRemountsAndDisposes));
        yield return Contract<CellFixtures>(nameof(CellFixtures.FactoryRejectsCurrentlyBuildingRootWithoutCorruption));
        yield return Contract<CellFixtures>(nameof(CellFixtures.FactoryRejectsReusedAndDisposedInstancesWithoutCorruption));
        yield return Contract<CellFixtures>(nameof(CellFixtures.FactorySubtypeRetainsAcrossKeyedReorderAndIndependentRebuild));
        yield return Contract<CellFixtures>(nameof(CellFixtures.FailedDirectChildRebuildResubmitsCanonicalParent));
        yield return Contract<CellFixtures>(nameof(CellFixtures.InputEqualitySchedulesOneBuild));
        yield return Contract<CellFixtures>(nameof(CellFixtures.KeyedRetirementContinuesAfterDisposeFailures));
        yield return Contract<CellFixtures>(nameof(CellFixtures.PositionalRetirementContinuesAfterDisposeFailures));
        yield return Contract<CellFixtures>(nameof(CellFixtures.RebuildRequestedDuringTransactionRunsOnNextUpdate));
        yield return Contract<CellFixtures>(nameof(CellFixtures.RemovedQueuedCellIsNotRebuiltAndDisposesOnce));
        yield return Contract<CellFixtures>(nameof(CellFixtures.RepeatedRebuildRequestsCoalesce));
        yield return Contract<CellFixtures>(nameof(CellFixtures.RootMountRetriesAfterInitialBuildFailure));
        yield return Contract<CellFixtures>(nameof(CellFixtures.SemanticInputEquivalenceKeepsNewestCallback));
        yield return Contract<CellFixtures>(nameof(CellFixtures.ThrowingInputEquivalenceRetriesSameSnapshot));
        yield return Contract<CellFixtures>(nameof(CellFixtures.TryPostReportsQueueAcceptance));
        yield return Contract<CellFixtures>(nameof(CellFixtures.WindowCloseCompletesAfterCleanupFailures));
        yield return Contract<ClickSequenceFixtures>(nameof(ClickSequenceFixtures.GenericCountsRespectBoundariesTargetsButtonsAndCancellation));
        yield return Contract<ClickSequenceFixtures>(nameof(ClickSequenceFixtures.RoutedInteractiveChildIsRelativeToEachHandler));
        yield return Contract<ClickSequenceFixtures>(nameof(ClickSequenceFixtures.TextSelectionUsesTheRoutedCountAndCaptureDoesNotCreateFalseClicks));
        yield return Contract<ClickSequenceFixtures>(nameof(ClickSequenceFixtures.TouchCountsArePerContactAndPenSequencesAreIndependent));
        yield return Contract<ClipPathInputFixtures>(nameof(ClipPathInputFixtures.CaptureContinuesOutsideClipUntilRelease));
        yield return Contract<ClipPathInputFixtures>(nameof(ClipPathInputFixtures.NestedClipPathsIntersect));
        yield return Contract<ClipPathInputFixtures>(nameof(ClipPathInputFixtures.NormalPointerAcquisitionRespectsClipPath));
        yield return Contract<ClipPathInputFixtures>(nameof(ClipPathInputFixtures.TransformedClipPathUsesMappedCoordinates));
        yield return Contract<DevToolsInputFixtures>(nameof(DevToolsInputFixtures.CaptureCancelAndValidation));
        yield return Contract<DevToolsInputFixtures>(nameof(DevToolsInputFixtures.OpaqueTargetsRejectOtherWindowsAndRemounts));
        yield return Contract<DevToolsInputFixtures>(nameof(DevToolsInputFixtures.OptInRoutingSettlementAndStaleTargets));
        yield return Contract<DevToolsInputFixtures>(nameof(DevToolsInputFixtures.QueuedTimeoutCannotExecuteLater));
        yield return Contract<DiagnosticsFixtures>(nameof(DiagnosticsFixtures.AutomaticAttachOnOpenIsIdempotentAndCloses));
        yield return Contract<DiagnosticsFixtures>(nameof(DiagnosticsFixtures.CaptureRequestRetriesAfterNotReady));
        yield return Contract<DiagnosticsFixtures>(nameof(DiagnosticsFixtures.InspectClickAndEscapeContract));
        yield return Contract<DiagnosticsFixtures>(nameof(DiagnosticsFixtures.ResolvedSemanticsAndEditorPrivacyContract));
        yield return Contract<DiagnosticsFixtures>(nameof(DiagnosticsFixtures.RuntimeOverrideInheritanceAndResetContract));
        yield return Contract<DiagnosticsFixtures>(nameof(DiagnosticsFixtures.SnapshotIdentityAndDeltaContract));
        yield return Contract<DragDropFixtures>(nameof(DragDropFixtures.ArbitrationReentrantResetAndCaptureCleanupContract));
        yield return Contract<DragDropFixtures>(nameof(DragDropFixtures.CallbackFailureTerminatesAndDoesNotRetry));
        yield return Contract<DragDropFixtures>(nameof(DragDropFixtures.CancellationContactAndCleanupContract));
        yield return Contract<DragDropFixtures>(nameof(DragDropFixtures.DescriptorReplacementRequeriesStationarySession));
        yield return Contract<DragDropFixtures>(nameof(DragDropFixtures.DropMutationAndPayloadOwnershipContract));
        yield return Contract<DragDropFixtures>(nameof(DragDropFixtures.RemovalDisableAndResetContract));
        yield return Contract<DragDropFixtures>(nameof(DragDropFixtures.ThresholdNegotiationTargetingAndClickContract));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.DuplicateAndCellContract));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.FocusContract));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.GeometryContract));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.KeyedRollbackRestoresHandle));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.KeyedSiblingMoveContract));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.LifecycleContract));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.MetricsCallbackRebuildAndBatchContract));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.MetricsCloseContract));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.MetricsContract));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.OwnerScopeFailureContract));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.PrimitiveMatrixContract));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.RetiredTreeDoesNotRetainThroughHandle));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.ScrollContract));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.VirtualContract));
        yield return Contract<ElementHandleFixtures>(nameof(ElementHandleFixtures.VirtualExtentValidationContract));
        yield return Contract<GradientFixtures>(nameof(GradientFixtures.LongGradientsCompileWithoutUnsupportedFallback));
        yield return Contract<InputFixtures>(nameof(InputFixtures.AutoFocusSelectsFirstEligibleNodeOnlyWhenFocusIsEmpty));
        yield return Contract<InputFixtures>(nameof(InputFixtures.AxisOverflowInteractionContract));
        yield return Contract<InputFixtures>(nameof(InputFixtures.CallbackReplacementUsesNewestDelegateWithoutInputEffect));
        yield return Contract<InputFixtures>(nameof(InputFixtures.ControlledTextEntryKeepsFocus));
        yield return Contract<InputFixtures>(nameof(InputFixtures.EditHandlesGraphemeClustersAndWordBoundaries));
        yield return Contract<InputFixtures>(nameof(InputFixtures.EntryBufferShapeIsRetainedAcrossReads));
        yield return Contract<InputFixtures>(nameof(InputFixtures.FocusCallbacksCoverUnavailableRemovalAndReentry));
        yield return Contract<InputFixtures>(nameof(InputFixtures.FocusReplacementDropsStaleFocus));
        yield return Contract<InputFixtures>(nameof(InputFixtures.FocusTransferAndTraversal));
        yield return Contract<InputFixtures>(nameof(InputFixtures.GenericTextCallbackRebuildStaysPresentationIdle));
        yield return Contract<InputFixtures>(nameof(InputFixtures.KeyboardCallbackFailuresCleanUpAndKeepQueuedSuffix));
        yield return Contract<InputFixtures>(nameof(InputFixtures.KeyboardCallbacksBubbleStopAndRepeat));
        yield return Contract<InputFixtures>(nameof(InputFixtures.KeyboardDefaultPreventionPreservesTextAndButtonRelease));
        yield return Contract<InputFixtures>(nameof(InputFixtures.KeyboardDrainConsumesThrowingEventOnceAndRetainsRest));
        yield return Contract<InputFixtures>(nameof(InputFixtures.KeyboardQueueAndRepeatLifecycle));
        yield return Contract<InputFixtures>(nameof(InputFixtures.KeyboardRepeatCancelsWhenFocusedEntryBecomesUnavailable));
        yield return Contract<InputFixtures>(nameof(InputFixtures.MacShortcutPolicyRoutesCommandAndOptionWord));
        yield return Contract<InputFixtures>(nameof(InputFixtures.MacWheelUnitScrollsTenPerUnit));
        yield return Contract<InputFixtures>(nameof(InputFixtures.MouseRemainsPrimaryWhileTouchIsHeld));
        yield return Contract<InputFixtures>(nameof(InputFixtures.NestedWheelOwnershipAndBoundary));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PenHoverKeepsContactStateUntilCancel));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PenIdentityIsDistinctFromTouchIdentity));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PointerAndKeyboardPressesShareStateSafely));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PointerCancelBalancesAnActiveRouteOnFocusLossAndInvalidation));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PointerCaptureRoutesMiddleDragUntilRelease));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PointerDrainConsumesThrowingEventOnceAndRetainsRest));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PointerEventsFlushStyleChangesInOrder));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PointerHoverActiveAndSiblingIsolation));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PointerHoverLifecycleOrderAndFailureContract));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PointerIdentityKeepsContactsIndependent));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PointerLifecycleBubblesStopsAndReportsAllMouseButtons));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PointerPrimaryAndPressureContract));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PointerReacquiresHoverAfterRebuild));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PointerResetStartsTheNextTouchSequence));
        yield return Contract<InputFixtures>(nameof(InputFixtures.PointerSelectsDeepestResolvedCursorAndClearsIt));
        yield return Contract<InputFixtures>(nameof(InputFixtures.RoutedKeyCallbackRebuildStaysPresentationIdle));
        yield return Contract<InputFixtures>(nameof(InputFixtures.ScrollStateSurvivesRebuild));
        yield return Contract<InputFixtures>(nameof(InputFixtures.ShapeStrokeHitChangesInvalidateInputContract));
        yield return Contract<InputFixtures>(nameof(InputFixtures.TextEntryCommandsAndSanitization));
        yield return Contract<InputFixtures>(nameof(InputFixtures.TextEntryPointerSelectionLifecycle));
        yield return Contract<InputFixtures>(nameof(InputFixtures.TouchCancelRetainsPreexistingFocus));
        yield return Contract<InputFixtures>(nameof(InputFixtures.TouchPrimaryWaitsForAllContactsToEnd));
        yield return Contract<InputFixtures>(nameof(InputFixtures.TransformRoutesHitsAndLocalPositions));
        yield return Contract<InputFixtures>(nameof(InputFixtures.UnhandledWheelStaysPresentationIdle));
        yield return Contract<LayoutFixtures>(nameof(LayoutFixtures.ComposedTreeMapsDeclarationsAndRelayouts));
        yield return Contract<LayoutFixtures>(nameof(LayoutFixtures.KeyedReorderRetainsYogaLayouts));
        yield return Contract<LayoutFixtures>(nameof(LayoutFixtures.LayoutIsStableAcrossRoots));
        yield return Contract<LayoutFixtures>(nameof(LayoutFixtures.LayoutTransitionGlidesComputedPosition));
        yield return Contract<LayoutFixtures>(nameof(LayoutFixtures.LogicalEdgesRespectDirection));
        yield return Contract<LayoutFixtures>(nameof(LayoutFixtures.StaticPositionIgnoresInsets));
        yield return Contract<LayoutFixtures>(nameof(LayoutFixtures.TextEntryUsesIntrinsicLineBoxHeight));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.CallbackAnimationContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.CellDisposeContinuesAfterPositionFailureContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.CloseIsolatesWindowPumpContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.DisposeRetainsPartialProgressContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.DisposedCellDeregistersContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.ExplicitVelocitySeedsFreshSimContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.FinishLandsExactlyOnTargetContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.ForcedCompletionSeedsNextRetargetFromTargetContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.InvalidConverterFailsBeforeRegistrationContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.InvalidVelocityAndSpecLeaveStateUntouchedContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.LandsAtSimResultNotTargetContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.LengthValidationContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.MotionVelocityAdditionPreservesShapeContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.MotionVelocityRoutingContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.PointRetargetCarriesIndependentVelocityContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.PointSpecRoutingContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.PreMountAnimationWaitsForWindowContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.PumpDefersReentrantRegistrationContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.PumpDeregisterStopsLaterParticleContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.PumpExceptionPreservesDeferredRegistrationContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.PumpRejectsReentrantSweepContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.PumpThrowingTickRemainsRegisteredContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.PumpWakesOnlyOnFirstRegistrationContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.RetargetAcrossDifferentSpanPreservesRealVelocityContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.RetargetPreservesVelocityContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.SameClockScaleChangeRecomputesValueContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.SetDuringBuildLeavesAnimUnchangedContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.SetStopsAndAllowsReuseContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.SnapDuringBuildAppliesValueContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.SnapStopsRunningAnimationWithoutInvalidateContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.ThrowingSpecLeavesAnimReusableContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.TimeScaleZeroCompletesInstantlyContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.TypedColorAnimationContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.VelocityGetterMatchesRetargetSeedContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.VelocityGetterPreservesRawColorComponentsContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.VelocityGetterReportsLiveAndRestingVelocityContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.VelocityGetterReportsPerDimensionPointVelocityContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.WindowCloseContinuesAfterAnimationFailureContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.WindowCloseTraversesSiblingCellsContract));
        yield return Contract<MotionFixtures>(nameof(MotionFixtures.WindowOwnsMotionClockContract));
        yield return Contract<PortalFixtures>(nameof(PortalFixtures.KeyedLifecycleFocusAccessibilityAndCaptureContract));
        yield return Contract<PortalFixtures>(nameof(PortalFixtures.OverlayOrderingInputAndGeometryContract));
        yield return Contract<ScrollbarFixtures>(nameof(ScrollbarFixtures.GeometryRenderingAndVisibilityContract));
        yield return Contract<ScrollbarFixtures>(nameof(ScrollbarFixtures.PointerDragAndCancellationContract));
        yield return Contract<ScrollbarFixtures>(nameof(ScrollbarFixtures.PublicMetricsAndJumpContract));
        yield return Contract<ShapeGeometryFixtures>(nameof(ShapeGeometryFixtures.GeneratedStrokeMappingUsesFullShapeBounds));
        yield return Contract<ShapeGeometryFixtures>(nameof(ShapeGeometryFixtures.MutableOpenContoursRefreshImplicitFillClosure));
        yield return Contract<ShapeGeometryFixtures>(nameof(ShapeGeometryFixtures.OpenContoursRemainOpenForStrokeConstruction));
        yield return Contract<ShapeGeometryFixtures>(nameof(ShapeGeometryFixtures.OpenContoursUseImplicitFillClosure));
        yield return Contract<ShapeGeometryFixtures>(nameof(ShapeGeometryFixtures.VectorViewportPreservesTranslationAndMapsShapeHits));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.AxisOverflowPrecedenceAndResetContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.BorderEdgePrecedenceResetAndMaskContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.BoxShadowPrecedenceCopyAndResetContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.BoxShadowTransitionContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.CursorInheritanceAndResetContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.DeclarationInlineSpillOrderContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.DirectionAndLogicalEdgeContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.OrderedCompositionAndGradientClearContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.OutlineStateResetTransitionAndStorageContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.ResolvePrecedenceAndResetContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.ShaderEffectOnlyReplacementContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.ShapeSideTransitionSelectorsSnapUniformStrokeContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.ShapeStrokeShorthandResolutionContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.ShapeStrokeTransitionContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.ShorthandLogicalCascadeContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.ShorthandTransitionSelectionContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.StateOnlyTransitionFallbackContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.StateStyleRetentionAndEqualityContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TextDecorationInheritanceStateAndStorageContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TextMaxLinesResolutionStateAndCacheContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TextShadowResolutionStorageAndDiffContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TextShadowValueValidationContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TextStrokeResolutionStorageAndDiffContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TextTransformInheritanceStateAndCacheContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TextWrapAndTrimmingStateInheritanceContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TransformStateTransitionAndGeometryContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TransitionBlobEasingContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TransitionDeclarationContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TransitionDelayAndPropertySelectionContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TransitionInterpolationAndRetargetContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TransitionSnapAndResetContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TransitionTimingSnapshotContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.TypographyInheritanceContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.VisibilityStateResetTransitionAndStorageContract));
        yield return Contract<StyleFixtures>(nameof(StyleFixtures.ZIndexRangeStateAndResetContract));
        yield return Contract<TextEditorInputFixtures>(nameof(TextEditorInputFixtures.KeyboardCompositionClipboardAndSubmit));
        yield return Contract<TextEditorInputFixtures>(nameof(TextEditorInputFixtures.NewVerticalRepeatDoesNotUsePreInputTime));
        yield return Contract<TextEditorInputFixtures>(nameof(TextEditorInputFixtures.PointerSelectsWordLineShiftAndFocusesController));
        yield return Contract<TextEditorInputFixtures>(nameof(TextEditorInputFixtures.ReadOnlyTabEscapesAndCommandsCanCancel));
        yield return Contract<TextEditorInputFixtures>(nameof(TextEditorInputFixtures.WheelScrollAndCaretBlinkUseEditorState));
        yield return Contract<TextInputPrimitivesFixtures>(nameof(TextInputPrimitivesFixtures.BuiltInDefaultsPrecedeThrowingObserversAndRetainQueuedSuffix));
        yield return Contract<TextInputPrimitivesFixtures>(nameof(TextInputPrimitivesFixtures.GenericCallbacksReceiveNormalizedUtf16Payloads));
        yield return Contract<TextInputPrimitivesFixtures>(nameof(TextInputPrimitivesFixtures.MountedCustomContainerContract));
        yield return Contract<TextInputPrimitivesFixtures>(nameof(TextInputPrimitivesFixtures.NativeTextInputLifecycleContract));
        yield return Contract<TextInputPrimitivesFixtures>(nameof(TextInputPrimitivesFixtures.SameDiffKeyboardAndTextCallbacksStaySynchronized));
        yield return Contract<TextInputPrimitivesFixtures>(nameof(TextInputPrimitivesFixtures.StaleTextEventsDropAcrossTransfersAndFocusCycles));
        yield return Contract<TextInputPrimitivesFixtures>(nameof(TextInputPrimitivesFixtures.TextCallbackStateStaysAbsentUntilConfigured));
        yield return Contract<TextInputPrimitivesFixtures>(nameof(TextInputPrimitivesFixtures.UnavailableOrRemovedFocusedClientsDropQueuedText));
        yield return Contract<TreeFixtures>(nameof(TreeFixtures.ButtonStyleSpillContract));
        yield return Contract<TreeFixtures>(nameof(TreeFixtures.ControlledEntryComposition));
        yield return Contract<TreeFixtures>(nameof(TreeFixtures.ExplicitControlledEntryValue));
        yield return Contract<TreeFixtures>(nameof(TreeFixtures.KeyedReconciliationContract));
        yield return Contract<TreeFixtures>(nameof(TreeFixtures.LeafDirtyUpdateContract));
        yield return Contract<TreeFixtures>(nameof(TreeFixtures.OutputAndKindReplacementContract));
        yield return Contract<TreeFixtures>(nameof(TreeFixtures.PositionalReconciliationContract));
        yield return Contract<TreeFixtures>(nameof(TreeFixtures.TextEntryControlledValueContract));
        yield return Contract<VulkanQueueWorkerFixtures>(nameof(VulkanQueueWorkerFixtures.WakeFailureDrainsFollowingMailboxAndQuiesces));
    }

    [Theory]
    [MemberData(nameof(Cases))]
    public void ContractReturnsTrue(Type fixtureType, string methodName)
    {
        var fixture = Activator.CreateInstance(fixtureType, true);
        var method = fixtureType.GetMethod(
            methodName,
            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);

        Assert.NotNull(fixture);
        Assert.NotNull(method);
        Assert.True(((Func<bool>)method.CreateDelegate(typeof(Func<bool>), fixture))());
    }

    [Theory]
    [InlineData("mount-mixed")]
    [InlineData("diff-mixed")]
    [InlineData("mount-duplicate")]
    [InlineData("diff-duplicate")]
    public void InvalidChildListsAreRejected(string scenario) =>
        Assert.True(new TreeFixtures().RejectsInvalidChildList(scenario));

    private static object[] Contract<TFixture>(string methodName) => [typeof(TFixture), methodName];
}
