version: 2

updates:
  - package-ecosystem: "nuget"
    directories:
      - "/Goo.InternalTextInterop"
      - "/tests/Goo.Tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
