<Project>
  <PropertyGroup>
    <GooReleaseVersion>0.5.2</GooReleaseVersion>
  </PropertyGroup>
  <!-- Custom Release configurations still require optimized G# output. -->
  <PropertyGroup Condition="$([System.String]::Copy('$(Configuration)').EndsWith('Release'))">
    <Optimize>true</Optimize>
  </PropertyGroup>
</Project>
