package Goo

import Hexa.NET.SDL3

internal partial class SdlHost {
  private func MapKey(key SDLScancode) SdlHostKey {
    return switch key {
      case SDLScancode.Space: SdlHostKey.Space
      case SDLScancode.Apostrophe: SdlHostKey.Apostrophe
      case SDLScancode.Comma: SdlHostKey.Comma
      case SDLScancode.Minus: SdlHostKey.Minus
      case SDLScancode.Period: SdlHostKey.Period
      case SDLScancode.Slash: SdlHostKey.Slash
      case SDLScancode.Scancode0: SdlHostKey.Number0
      case SDLScancode.Scancode1: SdlHostKey.Number1
      case SDLScancode.Scancode2: SdlHostKey.Number2
      case SDLScancode.Scancode3: SdlHostKey.Number3
      case SDLScancode.Scancode4: SdlHostKey.Number4
      case SDLScancode.Scancode5: SdlHostKey.Number5
      case SDLScancode.Scancode6: SdlHostKey.Number6
      case SDLScancode.Scancode7: SdlHostKey.Number7
      case SDLScancode.Scancode8: SdlHostKey.Number8
      case SDLScancode.Scancode9: SdlHostKey.Number9
      case SDLScancode.Semicolon: SdlHostKey.Semicolon
      case SDLScancode.Equals: SdlHostKey.Equal
      case SDLScancode.A: SdlHostKey.A
      case SDLScancode.B: SdlHostKey.B
      case SDLScancode.C: SdlHostKey.C
      case SDLScancode.D: SdlHostKey.D
      case SDLScancode.E: SdlHostKey.E
      case SDLScancode.F: SdlHostKey.F
      case SDLScancode.G: SdlHostKey.G
      case SDLScancode.H: SdlHostKey.H
      case SDLScancode.I: SdlHostKey.I
      case SDLScancode.J: SdlHostKey.J
      case SDLScancode.K: SdlHostKey.K
      case SDLScancode.L: SdlHostKey.L
      case SDLScancode.M: SdlHostKey.M
      case SDLScancode.N: SdlHostKey.N
      case SDLScancode.O: SdlHostKey.O
      case SDLScancode.P: SdlHostKey.P
      case SDLScancode.Q: SdlHostKey.Q
      case SDLScancode.R: SdlHostKey.R
      case SDLScancode.S: SdlHostKey.S
      case SDLScancode.T: SdlHostKey.T
      case SDLScancode.U: SdlHostKey.U
      case SDLScancode.V: SdlHostKey.V
      case SDLScancode.W: SdlHostKey.W
      case SDLScancode.X: SdlHostKey.X
      case SDLScancode.Y: SdlHostKey.Y
      case SDLScancode.Z: SdlHostKey.Z
      case SDLScancode.Leftbracket: SdlHostKey.LeftBracket
      case SDLScancode.Backslash: SdlHostKey.BackSlash
      case SDLScancode.Rightbracket: SdlHostKey.RightBracket
      case SDLScancode.Grave: SdlHostKey.GraveAccent
      case SDLScancode.International1: SdlHostKey.World1
      case SDLScancode.International2: SdlHostKey.World2
      case SDLScancode.Escape: SdlHostKey.Escape
      case SDLScancode.Return: SdlHostKey.Enter
      case SDLScancode.Tab: SdlHostKey.Tab
      case SDLScancode.Backspace: SdlHostKey.Backspace
      case SDLScancode.Insert: SdlHostKey.Insert
      case SDLScancode.Delete: SdlHostKey.Delete
      case SDLScancode.Right: SdlHostKey.Right
      case SDLScancode.Left: SdlHostKey.Left
      case SDLScancode.Down: SdlHostKey.Down
      case SDLScancode.Up: SdlHostKey.Up
      case SDLScancode.Pageup: SdlHostKey.PageUp
      case SDLScancode.Pagedown: SdlHostKey.PageDown
      case SDLScancode.Home: SdlHostKey.Home
      case SDLScancode.End: SdlHostKey.End
      case SDLScancode.Capslock: SdlHostKey.CapsLock
      case SDLScancode.Scrolllock: SdlHostKey.ScrollLock
      case SDLScancode.Numlockclear: SdlHostKey.NumLock
      case SDLScancode.Printscreen: SdlHostKey.PrintScreen
      case SDLScancode.Pause: SdlHostKey.Pause
      case SDLScancode.F1: SdlHostKey.F1
      case SDLScancode.F2: SdlHostKey.F2
      case SDLScancode.F3: SdlHostKey.F3
      case SDLScancode.F4: SdlHostKey.F4
      case SDLScancode.F5: SdlHostKey.F5
      case SDLScancode.F6: SdlHostKey.F6
      case SDLScancode.F7: SdlHostKey.F7
      case SDLScancode.F8: SdlHostKey.F8
      case SDLScancode.F9: SdlHostKey.F9
      case SDLScancode.F10: SdlHostKey.F10
      case SDLScancode.F11: SdlHostKey.F11
      case SDLScancode.F12: SdlHostKey.F12
      case SDLScancode.F13: SdlHostKey.F13
      case SDLScancode.F14: SdlHostKey.F14
      case SDLScancode.F15: SdlHostKey.F15
      case SDLScancode.F16: SdlHostKey.F16
      case SDLScancode.F17: SdlHostKey.F17
      case SDLScancode.F18: SdlHostKey.F18
      case SDLScancode.F19: SdlHostKey.F19
      case SDLScancode.F20: SdlHostKey.F20
      case SDLScancode.F21: SdlHostKey.F21
      case SDLScancode.F22: SdlHostKey.F22
      case SDLScancode.F23: SdlHostKey.F23
      case SDLScancode.F24: SdlHostKey.F24
      case SDLScancode.Kp0: SdlHostKey.Keypad0
      case SDLScancode.Kp1: SdlHostKey.Keypad1
      case SDLScancode.Kp2: SdlHostKey.Keypad2
      case SDLScancode.Kp3: SdlHostKey.Keypad3
      case SDLScancode.Kp4: SdlHostKey.Keypad4
      case SDLScancode.Kp5: SdlHostKey.Keypad5
      case SDLScancode.Kp6: SdlHostKey.Keypad6
      case SDLScancode.Kp7: SdlHostKey.Keypad7
      case SDLScancode.Kp8: SdlHostKey.Keypad8
      case SDLScancode.Kp9: SdlHostKey.Keypad9
      case SDLScancode.KpPeriod: SdlHostKey.KeypadDecimal
      case SDLScancode.KpDivide: SdlHostKey.KeypadDivide
      case SDLScancode.KpMultiply: SdlHostKey.KeypadMultiply
      case SDLScancode.KpMinus: SdlHostKey.KeypadSubtract
      case SDLScancode.KpPlus: SdlHostKey.KeypadAdd
      case SDLScancode.KpEnter: SdlHostKey.KeypadEnter
      case SDLScancode.KpEquals: SdlHostKey.KeypadEqual
      case SDLScancode.Lshift: SdlHostKey.ShiftLeft
      case SDLScancode.Lctrl: SdlHostKey.ControlLeft
      case SDLScancode.Lalt: SdlHostKey.AltLeft
      case SDLScancode.Lgui: SdlHostKey.SuperLeft
      case SDLScancode.Rshift: SdlHostKey.ShiftRight
      case SDLScancode.Rctrl: SdlHostKey.ControlRight
      case SDLScancode.Ralt: SdlHostKey.AltRight
      case SDLScancode.Rgui: SdlHostKey.SuperRight
      case SDLScancode.Application: SdlHostKey.Menu
      case SDLScancode.Menu: SdlHostKey.Menu
      case _: SdlHostKey.Unknown
    }
  }
}
