package Goo

import Hexa.NET.SDL3

internal partial class SdlHost {
  private func MapKey(key SDLScancode) Key -> switch key {
    case SDLScancode.Space: Key.Space
    case SDLScancode.Apostrophe: Key.Apostrophe
    case SDLScancode.Comma: Key.Comma
    case SDLScancode.Minus: Key.Minus
    case SDLScancode.Period: Key.Period
    case SDLScancode.Slash: Key.Slash
    case SDLScancode.Scancode0: Key.Number0
    case SDLScancode.Scancode1: Key.Number1
    case SDLScancode.Scancode2: Key.Number2
    case SDLScancode.Scancode3: Key.Number3
    case SDLScancode.Scancode4: Key.Number4
    case SDLScancode.Scancode5: Key.Number5
    case SDLScancode.Scancode6: Key.Number6
    case SDLScancode.Scancode7: Key.Number7
    case SDLScancode.Scancode8: Key.Number8
    case SDLScancode.Scancode9: Key.Number9
    case SDLScancode.Semicolon: Key.Semicolon
    case SDLScancode.Equals: Key.Equal
    case SDLScancode.A: Key.A
    case SDLScancode.B: Key.B
    case SDLScancode.C: Key.C
    case SDLScancode.D: Key.D
    case SDLScancode.E: Key.E
    case SDLScancode.F: Key.F
    case SDLScancode.G: Key.G
    case SDLScancode.H: Key.H
    case SDLScancode.I: Key.I
    case SDLScancode.J: Key.J
    case SDLScancode.K: Key.K
    case SDLScancode.L: Key.L
    case SDLScancode.M: Key.M
    case SDLScancode.N: Key.N
    case SDLScancode.O: Key.O
    case SDLScancode.P: Key.P
    case SDLScancode.Q: Key.Q
    case SDLScancode.R: Key.R
    case SDLScancode.S: Key.S
    case SDLScancode.T: Key.T
    case SDLScancode.U: Key.U
    case SDLScancode.V: Key.V
    case SDLScancode.W: Key.W
    case SDLScancode.X: Key.X
    case SDLScancode.Y: Key.Y
    case SDLScancode.Z: Key.Z
    case SDLScancode.Leftbracket: Key.LeftBracket
    case SDLScancode.Backslash: Key.BackSlash
    case SDLScancode.Rightbracket: Key.RightBracket
    case SDLScancode.Grave: Key.GraveAccent
    case SDLScancode.International1: Key.World1
    case SDLScancode.International2: Key.World2
    case SDLScancode.Escape: Key.Escape
    case SDLScancode.Return: Key.Enter
    case SDLScancode.Tab: Key.Tab
    case SDLScancode.Backspace: Key.Backspace
    case SDLScancode.Insert: Key.Insert
    case SDLScancode.Delete: Key.Delete
    case SDLScancode.Right: Key.Right
    case SDLScancode.Left: Key.Left
    case SDLScancode.Down: Key.Down
    case SDLScancode.Up: Key.Up
    case SDLScancode.Pageup: Key.PageUp
    case SDLScancode.Pagedown: Key.PageDown
    case SDLScancode.Home: Key.Home
    case SDLScancode.End: Key.End
    case SDLScancode.Capslock: Key.CapsLock
    case SDLScancode.Scrolllock: Key.ScrollLock
    case SDLScancode.Numlockclear: Key.NumLock
    case SDLScancode.Printscreen: Key.PrintScreen
    case SDLScancode.Pause: Key.Pause
    case SDLScancode.F1: Key.F1
    case SDLScancode.F2: Key.F2
    case SDLScancode.F3: Key.F3
    case SDLScancode.F4: Key.F4
    case SDLScancode.F5: Key.F5
    case SDLScancode.F6: Key.F6
    case SDLScancode.F7: Key.F7
    case SDLScancode.F8: Key.F8
    case SDLScancode.F9: Key.F9
    case SDLScancode.F10: Key.F10
    case SDLScancode.F11: Key.F11
    case SDLScancode.F12: Key.F12
    case SDLScancode.F13: Key.F13
    case SDLScancode.F14: Key.F14
    case SDLScancode.F15: Key.F15
    case SDLScancode.F16: Key.F16
    case SDLScancode.F17: Key.F17
    case SDLScancode.F18: Key.F18
    case SDLScancode.F19: Key.F19
    case SDLScancode.F20: Key.F20
    case SDLScancode.F21: Key.F21
    case SDLScancode.F22: Key.F22
    case SDLScancode.F23: Key.F23
    case SDLScancode.F24: Key.F24
    case SDLScancode.Kp0: Key.Keypad0
    case SDLScancode.Kp1: Key.Keypad1
    case SDLScancode.Kp2: Key.Keypad2
    case SDLScancode.Kp3: Key.Keypad3
    case SDLScancode.Kp4: Key.Keypad4
    case SDLScancode.Kp5: Key.Keypad5
    case SDLScancode.Kp6: Key.Keypad6
    case SDLScancode.Kp7: Key.Keypad7
    case SDLScancode.Kp8: Key.Keypad8
    case SDLScancode.Kp9: Key.Keypad9
    case SDLScancode.KpPeriod: Key.KeypadDecimal
    case SDLScancode.KpDivide: Key.KeypadDivide
    case SDLScancode.KpMultiply: Key.KeypadMultiply
    case SDLScancode.KpMinus: Key.KeypadSubtract
    case SDLScancode.KpPlus: Key.KeypadAdd
    case SDLScancode.KpEnter: Key.KeypadEnter
    case SDLScancode.KpEquals: Key.KeypadEqual
    case SDLScancode.Lshift: Key.ShiftLeft
    case SDLScancode.Lctrl: Key.ControlLeft
    case SDLScancode.Lalt: Key.AltLeft
    case SDLScancode.Lgui: Key.SuperLeft
    case SDLScancode.Rshift: Key.ShiftRight
    case SDLScancode.Rctrl: Key.ControlRight
    case SDLScancode.Ralt: Key.AltRight
    case SDLScancode.Rgui: Key.SuperRight
    case SDLScancode.Application: Key.Menu
    case SDLScancode.Menu: Key.Menu
    case _: Key.Unknown
  }
}
