<Project>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)FailedIdleFixtureAssemblyInfo.gs"
             Link="FailedIdleFixtureAssemblyInfo.gs" />
    <Compile Include="$(MSBuildThisFileDirectory)FailedIdleFixture.gs"
             Link="FailedIdleFixture.gs" />
  </ItemGroup>
</Project>
